"""Added comment song table constrait to be 1:N relation

Revision ID: 0bf3a35ccc81
Revises: 679bfb83c77e
Create Date: 2025-12-14 21:14:13.937870

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0bf3a35ccc81'
down_revision = '679bfb83c77e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
