"""Created a playlist model

Revision ID: 2f6fef0cc245
Revises: 0bf3a35ccc81
Create Date: 2025-12-15 09:17:41.611094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6fef0cc245'
down_revision = '0bf3a35ccc81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_song',
    sa.Column('playlist_id', sa.Uuid(), nullable=False),
    sa.Column('song_id', sa.Uuid(), nullable=False),
    sa.Column('filter', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    op.create_index(op.f('ix_playlist_song_playlist_id'), 'playlist_song', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_song_song_id'), 'playlist_song', ['song_id'], unique=False)
    op.create_unique_constraint(None, 'comment_song', ['comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment_song', type_='unique')
    op.drop_index(op.f('ix_playlist_song_song_id'), table_name='playlist_song')
    op.drop_index(op.f('ix_playlist_song_playlist_id'), table_name='playlist_song')
    op.drop_table('playlist_song')
    op.drop_table('playlist')
    # ### end Alembic commands ###
