"""Added file table

Revision ID: 4aed319b149c
Revises: b2437a6523e3
Create Date: 2025-12-06 21:29:27.324983

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4aed319b149c'
down_revision = 'b2437a6523e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('mime', sa.String(), nullable=False),
                    sa.Column('original_name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('users', 'username',
                    existing_type=sa.TEXT(),
                    type_=sa.String(length=32),
                    existing_nullable=False)
    op.alter_column('users', 'email',
                    existing_type=sa.TEXT(),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    op.alter_column('users', 'salt',
                    existing_type=sa.TEXT(),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.TEXT(),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('users', 'deleted_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    type_=sa.DateTime(),
                    existing_nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'deleted_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=True)
    op.alter_column('users', 'updated_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
                    existing_type=sa.DateTime(),
                    type_=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.String(length=256),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('users', 'salt',
                    existing_type=sa.String(length=255),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('users', 'email',
                    existing_type=sa.String(length=256),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('users', 'username',
                    existing_type=sa.String(length=32),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.drop_table('file')
    # ### end Alembic commands ###
