"""Added comment tables

Revision ID: 679bfb83c77e
Revises: e802aa3a99c1
Create Date: 2025-12-14 20:12:22.396902

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '679bfb83c77e'
down_revision = 'e802aa3a99c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('created_by_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_comment_created_at'), 'comment', ['created_at'], unique=False)
    op.create_table('comment_song',
                    sa.Column('comment_id', sa.Uuid(), nullable=False),
                    sa.Column('song_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('comment_id', 'song_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_song')
    op.drop_index(op.f('ix_comment_created_at'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
