"""Added file duration field

Revision ID: 69215f253bc8
Revises: aa99c319bc58
Create Date: 2025-12-13 18:04:42.601116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69215f253bc8'
down_revision = 'aa99c319bc58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'duration')
    # ### end Alembic commands ###
