"""Added group

Revision ID: 6fb228e19a95
Revises: 72d2a82b5bca
Create Date: 2025-12-12 18:37:22.292967

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6fb228e19a95'
down_revision = '72d2a82b5bca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('file_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('author_group',
                    sa.Column('author_id', sa.Uuid(), nullable=False),
                    sa.Column('group_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.PrimaryKeyConstraint('author_id', 'group_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_group')
    op.drop_table('group')
    # ### end Alembic commands ###
