"""Added foreign key constraints

Revision ID: 791f8ccb0d5a
Revises: 69215f253bc8
Create Date: 2025-12-14 09:26:45.128678

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '791f8ccb0d5a'
down_revision = '69215f253bc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('author_file_id_fkey'), 'author', type_='foreignkey')
    op.create_foreign_key(None, 'author', 'file', ['file_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('author_group_author_id_fkey'), 'author_group', type_='foreignkey')
    op.drop_constraint(op.f('author_group_group_id_fkey'), 'author_group', type_='foreignkey')
    op.create_foreign_key(None, 'author_group', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'author_group', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('group_file_id_fkey'), 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'file', ['file_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('song_release_song_id_fkey'), 'song_release', type_='foreignkey')
    op.create_foreign_key(None, 'song_release', 'song', ['song_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('song_release_author_author_id_fkey'), 'song_release_author', type_='foreignkey')
    op.drop_constraint(op.f('song_release_author_song_release_id_fkey'), 'song_release_author', type_='foreignkey')
    op.create_foreign_key(None, 'song_release_author', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'song_release_author', 'song_release', ['song_release_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('song_release_file_song_release_id_fkey'), 'song_release_file', type_='foreignkey')
    op.drop_constraint(op.f('song_release_file_file_id_fkey'), 'song_release_file', type_='foreignkey')
    op.create_foreign_key(None, 'song_release_file', 'file', ['file_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'song_release_file', 'song_release', ['song_release_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('song_release_group_song_release_id_fkey'), 'song_release_group', type_='foreignkey')
    op.drop_constraint(op.f('song_release_group_group_id_fkey'), 'song_release_group', type_='foreignkey')
    op.create_foreign_key(None, 'song_release_group', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'song_release_group', 'song_release', ['song_release_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song_release_group', type_='foreignkey')
    op.drop_constraint(None, 'song_release_group', type_='foreignkey')
    op.create_foreign_key(op.f('song_release_group_group_id_fkey'), 'song_release_group', 'group', ['group_id'], ['id'])
    op.create_foreign_key(op.f('song_release_group_song_release_id_fkey'), 'song_release_group', 'song_release',
                          ['song_release_id'], ['id'])
    op.drop_constraint(None, 'song_release_file', type_='foreignkey')
    op.drop_constraint(None, 'song_release_file', type_='foreignkey')
    op.create_foreign_key(op.f('song_release_file_file_id_fkey'), 'song_release_file', 'file', ['file_id'], ['id'])
    op.create_foreign_key(op.f('song_release_file_song_release_id_fkey'), 'song_release_file', 'song_release',
                          ['song_release_id'], ['id'])
    op.drop_constraint(None, 'song_release_author', type_='foreignkey')
    op.drop_constraint(None, 'song_release_author', type_='foreignkey')
    op.create_foreign_key(op.f('song_release_author_song_release_id_fkey'), 'song_release_author', 'song_release',
                          ['song_release_id'], ['id'])
    op.create_foreign_key(op.f('song_release_author_author_id_fkey'), 'song_release_author', 'author', ['author_id'],
                          ['id'])
    op.drop_constraint(None, 'song_release', type_='foreignkey')
    op.create_foreign_key(op.f('song_release_song_id_fkey'), 'song_release', 'song', ['song_id'], ['id'])
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key(op.f('group_file_id_fkey'), 'group', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'author_group', type_='foreignkey')
    op.drop_constraint(None, 'author_group', type_='foreignkey')
    op.create_foreign_key(op.f('author_group_group_id_fkey'), 'author_group', 'group', ['group_id'], ['id'])
    op.create_foreign_key(op.f('author_group_author_id_fkey'), 'author_group', 'author', ['author_id'], ['id'])
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.create_foreign_key(op.f('author_file_id_fkey'), 'author', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
