"""Added song models

Revision ID: aa99c319bc58
Revises: 6fb228e19a95
Create Date: 2025-12-13 16:35:38.054320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa99c319bc58'
down_revision = '6fb228e19a95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_release',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('song_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('lyrics', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_release_created_at'), 'song_release', ['created_at'], unique=False)
    op.create_index(op.f('ix_song_release_song_id'), 'song_release', ['song_id'], unique=False)
    op.create_table('song_release_author',
    sa.Column('song_release_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['song_release_id'], ['song_release.id'], ),
    sa.PrimaryKeyConstraint('song_release_id', 'author_id')
    )
    op.create_table('song_release_file',
    sa.Column('song_release_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['song_release_id'], ['song_release.id'], ),
    sa.PrimaryKeyConstraint('song_release_id', 'file_id')
    )
    op.create_index(op.f('ix_song_release_file_file_id'), 'song_release_file', ['file_id'], unique=False)
    op.create_index(op.f('ix_song_release_file_song_release_id'), 'song_release_file', ['song_release_id'], unique=False)
    op.create_table('song_release_group',
    sa.Column('song_release_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['song_release_id'], ['song_release.id'], ),
    sa.PrimaryKeyConstraint('song_release_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_release_group')
    op.drop_index(op.f('ix_song_release_file_song_release_id'), table_name='song_release_file')
    op.drop_index(op.f('ix_song_release_file_file_id'), table_name='song_release_file')
    op.drop_table('song_release_file')
    op.drop_table('song_release_author')
    op.drop_index(op.f('ix_song_release_song_id'), table_name='song_release')
    op.drop_index(op.f('ix_song_release_created_at'), table_name='song_release')
    op.drop_table('song_release')
    op.drop_table('song')
    # ### end Alembic commands ###
