"""Fixing not being able to delete song

Revision ID: e802aa3a99c1
Revises: 791f8ccb0d5a
Create Date: 2025-12-14 09:29:06.570716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e802aa3a99c1'
down_revision = '791f8ccb0d5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song_release', 'song_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song_release', 'song_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
