/* tslint:disable */
/* eslint-disable */
/**
 * Dev FastAPI example application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Data {
    'id'?: number;
    'username': string;
    'email': string;
    'created_at'?: string;
    'updated_at'?: string;
    'deleted_at'?: string;
    'token'?: UserTokenData;
}
export interface ErrorResponse {
    'app_exception'?: string;
    'context'?: object | null;
}
export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface UserAuthOutData {
    'id'?: number | null;
    'username': string;
    'email': string;
    'created_at'?: string | null;
    'updated_at'?: string | null;
    'deleted_at'?: string | null;
    'token'?: UserTokenData | null;
}
export interface UserInCreate {
    'username': string;
    'password': string;
    'email': string;
}
export interface UserInSignIn {
    'password': string;
    'email': string;
}
export interface UserInUpdate {
    'username'?: string | null;
    'password'?: string | null;
    'email'?: string | null;
}
export interface UserOutData {
    'id'?: number | null;
    'username': string;
    'email': string;
    'created_at'?: string | null;
    'updated_at'?: string | null;
    'deleted_at'?: string | null;
}
export interface UserResponse {
    'message'?: string;
    'data': Data;
    'detail'?: object | null;
}
export interface UserTokenData {
    'access_token'?: string | null;
    'token_type'?: string | null;
}
export interface ValidationError {
    'loc': Array<ValidationErrorLocInner>;
    'msg': string;
    'type': string;
}
export interface ValidationErrorLocInner {
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create new users.
         * @summary Auth:Info
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authInfoApiV1AuthInfoGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/auth/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication RWAPIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create new users.
         * @summary Auth:Signin
         * @param {UserInSignIn} userInSignIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSigninApiV1AuthSigninPost: async (userInSignIn: UserInSignIn, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userInSignIn' is not null or undefined
            assertParamExists('authSigninApiV1AuthSigninPost', 'userInSignIn', userInSignIn)
            const localVarPath = `/api/v1/auth/signin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userInSignIn, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Signup new users.
         * @summary Auth:Signup
         * @param {UserInCreate} userInCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSignupApiV1AuthSignupPost: async (userInCreate: UserInCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userInCreate' is not null or undefined
            assertParamExists('authSignupApiV1AuthSignupPost', 'userInCreate', userInCreate)
            const localVarPath = `/api/v1/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userInCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Create new users.
         * @summary Auth:Info
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authInfoApiV1AuthInfoGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authInfoApiV1AuthInfoGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authInfoApiV1AuthInfoGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create new users.
         * @summary Auth:Signin
         * @param {UserInSignIn} userInSignIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSigninApiV1AuthSigninPost(userInSignIn: UserInSignIn, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authSigninApiV1AuthSigninPost(userInSignIn, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authSigninApiV1AuthSigninPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Signup new users.
         * @summary Auth:Signup
         * @param {UserInCreate} userInCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSignupApiV1AuthSignupPost(userInCreate: UserInCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authSignupApiV1AuthSignupPost(userInCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authSignupApiV1AuthSignupPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Create new users.
         * @summary Auth:Info
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authInfoApiV1AuthInfoGet(options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.authInfoApiV1AuthInfoGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Create new users.
         * @summary Auth:Signin
         * @param {UserInSignIn} userInSignIn 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSigninApiV1AuthSigninPost(userInSignIn: UserInSignIn, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.authSigninApiV1AuthSigninPost(userInSignIn, options).then((request) => request(axios, basePath));
        },
        /**
         * Signup new users.
         * @summary Auth:Signup
         * @param {UserInCreate} userInCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSignupApiV1AuthSignupPost(userInCreate: UserInCreate, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.authSignupApiV1AuthSignupPost(userInCreate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * Create new users.
     * @summary Auth:Info
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authInfoApiV1AuthInfoGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authInfoApiV1AuthInfoGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create new users.
     * @summary Auth:Signin
     * @param {UserInSignIn} userInSignIn 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authSigninApiV1AuthSigninPost(userInSignIn: UserInSignIn, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authSigninApiV1AuthSigninPost(userInSignIn, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Signup new users.
     * @summary Auth:Signup
     * @param {UserInCreate} userInCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authSignupApiV1AuthSignupPost(userInCreate: UserInCreate, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authSignupApiV1AuthSignupPost(userInCreate, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Hello
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        helloApiV1UsersHelloGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/hello`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User:Delete-By-Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userDeleteByIdApiV1UsersDelete: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication RWAPIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User:Info-By-Id
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userInfoByIdApiV1UsersUserIdGet: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('userInfoByIdApiV1UsersUserIdGet', 'userId', userId)
            const localVarPath = `/api/v1/users/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication RWAPIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User:Patch-By-Id
         * @param {UserInUpdate} userInUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userPatchByIdApiV1UsersPatch: async (userInUpdate: UserInUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userInUpdate' is not null or undefined
            assertParamExists('userPatchByIdApiV1UsersPatch', 'userInUpdate', userInUpdate)
            const localVarPath = `/api/v1/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication RWAPIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userInUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Users:All
         * @param {number | null} [skip] 
         * @param {number | null} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAllApiV1UsersGet: async (skip?: number | null, limit?: number | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Hello
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async helloApiV1UsersHelloGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.helloApiV1UsersHelloGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.helloApiV1UsersHelloGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User:Delete-By-Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userDeleteByIdApiV1UsersDelete(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userDeleteByIdApiV1UsersDelete(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.userDeleteByIdApiV1UsersDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User:Info-By-Id
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userInfoByIdApiV1UsersUserIdGet(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userInfoByIdApiV1UsersUserIdGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.userInfoByIdApiV1UsersUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User:Patch-By-Id
         * @param {UserInUpdate} userInUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userPatchByIdApiV1UsersPatch(userInUpdate: UserInUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userPatchByIdApiV1UsersPatch(userInUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.userPatchByIdApiV1UsersPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Users:All
         * @param {number | null} [skip] 
         * @param {number | null} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersAllApiV1UsersGet(skip?: number | null, limit?: number | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersAllApiV1UsersGet(skip, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersAllApiV1UsersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @summary Hello
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        helloApiV1UsersHelloGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.helloApiV1UsersHelloGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User:Delete-By-Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userDeleteByIdApiV1UsersDelete(options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.userDeleteByIdApiV1UsersDelete(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User:Info-By-Id
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userInfoByIdApiV1UsersUserIdGet(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.userInfoByIdApiV1UsersUserIdGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User:Patch-By-Id
         * @param {UserInUpdate} userInUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userPatchByIdApiV1UsersPatch(userInUpdate: UserInUpdate, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.userPatchByIdApiV1UsersPatch(userInUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Users:All
         * @param {number | null} [skip] 
         * @param {number | null} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersAllApiV1UsersGet(skip?: number | null, limit?: number | null, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.usersAllApiV1UsersGet(skip, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary Hello
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public helloApiV1UsersHelloGet(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).helloApiV1UsersHelloGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary User:Delete-By-Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userDeleteByIdApiV1UsersDelete(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).userDeleteByIdApiV1UsersDelete(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary User:Info-By-Id
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userInfoByIdApiV1UsersUserIdGet(userId: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).userInfoByIdApiV1UsersUserIdGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary User:Patch-By-Id
     * @param {UserInUpdate} userInUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userPatchByIdApiV1UsersPatch(userInUpdate: UserInUpdate, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).userPatchByIdApiV1UsersPatch(userInUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Users:All
     * @param {number | null} [skip] 
     * @param {number | null} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersAllApiV1UsersGet(skip?: number | null, limit?: number | null, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersAllApiV1UsersGet(skip, limit, options).then((request) => request(this.axios, this.basePath));
    }
}



